services:
  ps-builder-s:
    build: ./ps-builder
    container_name: ps-builder
    env_file: .env
    volumes:
      - $TARGET_DIR:$TARGET_DIR

  ps-nginx-s:
    build: ./ps-nginx
    container_name: ps-nginx
    depends_on:
      - ps-builder-s
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - $TARGET_DIR:/var/www/html:ro
      - ./ps-nginx/nginx.conf:/etc/nginx/nginx.conf
